version: '3.8'
services:
  db:
    build: ./database/
    container_name: tcc-postgres
    image: tcc-image:v0
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tcc"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres
  pg-admin:
    image: dpage/pgadmin4
    container_name: tcc_pgadmin
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    # depends_on: 
    #   - db
    ports:
      - "8080:80"
    volumes:
      - './pgadmin-data:/var/lib/pgadmin'
    # networks:
    #   - postgres
  mongodb:
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    container_name: tcc-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${POSTGRES_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - postgres
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${POSTGRES_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${POSTGRES_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_CONN}
      ME_CONFIG_BASICAUTH: false
    networks:
      - postgres
  api: 
    build: .
    container_name: tcc-api
    image: tcc-api:v0
    environment:
      APIKEY: ${APIKEY}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      HOST: ${HOST}
      MONGO_CONN: ${MONGO_CONN}
    ports:
      - "3001:3001"
    networks:
      - postgres
    # depends_on:
    #   db:
    #     condition: service_healthy
networks:
  postgres:
    driver: bridge