CREATE TABLE IF NOT EXISTS "Ifes" (
    id SMALLSERIAL PRIMARY KEY,
    code VARCHAR,
    acronym VARCHAR,
    name VARCHAR
);

INSERT INTO "Ifes" (id,code,acronym,name) VALUES (1,'26269','UNIRIO','Universidade Federal do Estado do Rio de Janeiro');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (2,'26352','UFABC','Fundação Universidade Federal do ABC');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (3,'26275','FUFAC','Fundação Universidade Federal do Acre');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (4,'26231','UFAL','Universidade Federal de Alagoas');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (5,'26270','FUAM','Fundação Universidade do Amazonas');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (6,'26456','UFAPE','Universidade Federal do Agreste de Pernambuco');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (7,'26232','UFBA','Universidade Federal da Bahia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (8,'26233','UFCE','Universidade Federal do Ceará');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (9,'26449','UFCA','Universidade Federal do Cariri');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (10,'26452','UFCAT','Universidade Federal de Catalão');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (11,'26252','UFCG','Universidade Federal de Campina Grande');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (12,'26284','UFCSPA','Fundação Universidade Federal de Ciências da Saúde de Porto Alegre');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (13,'26455','UFDPar','Universidade Federal do Delta do Parnaíba');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (14,'26264','UFERSA','Universidade Federal Rural do Semi-Árido');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (15,'26234','UFES','Universidade Federal do Espírito Santo');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (16,'26236','UFF','Universidade Federal Fluminense');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (17,'26440','UFFS','Universidade Federal da Fronteira Sul');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (18,'26235','UFG','Universidade Federal de Goiás');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (19,'26350','UFGD','Fundação Universidade Federal da Grande Dourados');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (20,'26453','UFJ','Universidade Federal de Jataí');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (21,'26237','UFJF','Universidade Federal de Juiz de Fora');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (22,'26263','UFLA','Universidade Federal de Lavras');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (23,'26272','FUMA','Fundação Universidade do Maranhão');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (24,'26238','UFMG','Universidade Federal de Minas Gerais');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (25,'26283','FUFMS','Fundação Universidade Federal do Mato Grosso do Sul');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (26,'26276','FUFMT','Fundação Universidade Federal do Mato Grosso');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (27,'26457','UFNT','Universidade Federal do Norte do Tocantins');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (28,'26447','UFOB','Universidade Federal do Oeste da Bahia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (29,'26277','UFOP','Universidade Federal de Ouro Preto');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (30,'26441','UFOPA','Universidade Federal do Oeste do Pará');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (31,'26239','UFPA','Universidade Federal do Pará');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (32,'26240','UFPB','Universidade Federal da Paraíba');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (33,'26242','UFPE','Universidade Federal de Pernambuco');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (34,'26278','UFPel','Fundação Universidade Federal de Pelotas');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (35,'26279','FUFPI','Fundação Universidade Federal do Piauí');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (36,'26241','UFPR','Universidade Federal do Paraná');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (37,'26454','UFR','Universidade Federal de Rondonópolis');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (38,'26253','UFRA','Universidade Federal Rural da Amazônia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (39,'26351','UFRB','Universidade Federal do Recôncavo da Bahia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (40,'26244','UFRGS','Universidade Federal do Rio Grande do Sul');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (41,'26245','UFRJ','Universidade Federal do Rio de Janeiro');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (42,'26243','UFRN','Universidade Federal do Rio Grande do Norte');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (43,'26248','UFRPE','Universidade Federal Rural de Pernambuco');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (44,'26250','UFRR','Universidade Federal de Roraima');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (45,'26249','UFRRJ','Universidade Federal Rural do Rio de Janeiro');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (46,'26281','FUFS','Fundação Universidade Federal de Sergipe');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (47,'26450','UFSB','Universidade Federal do Sul da Bahia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (48,'26246','UFSC','Universidade Federal de Santa Catarina');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (49,'26280','FUFSCar','Fundação Universidade Federal de São Carlos');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (50,'26285','UFSJ','Fundação Universidade Federal de São João Del-Rei');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (51,'26247','UFSM','Universidade Federal de Santa Maria');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (52,'26251','UFT','Fundação Universidade Federal do Tocantins');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (53,'26254','UFTM','Universidade Federal do Triângulo Mineiro');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (54,'26274','FUFU','Fundação Universidade Federal de Uberlândia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (55,'26282','UFV','Universidade Federal de Viçosa');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (56,'26255','UFVJM','Universidade Federal dos Vales do Jequitinhonha e Mucuri');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (57,'26271','FUB','Fundação Universidade de Brasília');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (58,'26260','UNIFAL','Universidade Federal de Alfenas');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (59,'26286','FUFAP','Fundação Universidade Federal do Amapá');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (60,'26261','UNIFEI','Universidade Federal de Itajubá');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (61,'26262','UNIFESP','Universidade Federal de São Paulo');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (62,'26448','UNIFESSPA','Universidade Federal do Sul e Sudeste do Pará');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (63,'26267','UNILA','Universidade Federal da Integração Latino-Americana');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (64,'26442','UNILAB','Universidade da Integração Internacional da Lusofonia Afro-Brasileira');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (65,'26266','UNIPAMPA','Fundação Universidade Federal do Pampa');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (66,'26268','FUFRO','Fundação Universidade Federal de Rondônia');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (67,'26230','UNIVASF','Fundação Universidade Federal do Vale do São Francisco');
INSERT INTO "Ifes" (id,code,acronym,name) VALUES (68,'26258','UTFPR','Universidade Tecnológica Federal do Paraná');