# Usar a imagem oficial do PostgreSQL como imagem base
FROM postgres

# Definir as variáveis de ambiente para o usuário e senha do PostgreSQL
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG POSTGRES_PORT
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_PORT=${POSTGRES_PORT}

# Copiar o script de inicialização para o contêiner
COPY ./init-db /docker-entrypoint-initdb.d/

# Expor a porta para permitir conexões externas
EXPOSE ${POSTGRES_PORT}