name: CI/CD
on:
  push:
    branches: ["main", "cicd-code-update"]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
env:
  WEBAPP_NAME: "tcc-convenio-backend"
  RESOURCE_GROUP_NAME: "tcc-convenio"
  NODE_VERSION: "18.x"
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.11.0
        with: 
          context: ./
          file: ./dockerfile
          push: true
          tags: |
            lucassds/tcc-convenio-backend:latest
            lucassds/tcc-convenio-backend:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          resource-group-name: ${{ env.RESOURCE_GROUP_NAME }}
          publish-profile: ${{ env.AZURE_PUBLISH_PROFILE }}
          images: lucassds/tcc-convenio-backend:${{github.run_number}}

